import { defineParser } from '@kubb/fabric-core/parsers'

/**
 * PDF parser that handles PDF file generation using react-pdf
 * This parser is used when the file extension is .pdf
 */
export const pdfParser = defineParser({
  name: 'pdf',
  extNames: ['.pdf'],
  async install() {
    // Optional: Validate react-pdf is available
  },
  async parse(file) {
    // For PDF files, we expect the sources to contain a special marker
    // indicating that react-pdf rendering should be used
    // The actual PDF generation happens in the PDF plugin via react-pdf's renderToFile
    
    // Return a marker that indicates this file needs PDF rendering
    // The actual content will be generated by the PDF plugin
    const pdfContent = file.sources.map((item) => item.value).join('\n')
    return pdfContent || ''
  },
})
