packages:
  - packages/*
  - examples/*

catalog:
  '@types/node': ^20.19.27
  '@types/react': ^19.2.7
  '@types/react-reconciler': 0.32.0
  '@size-limit/file': ^11.2.0
  'size-limit': ^11.2.0
  react: 19.2.1
  react-reconciler: 0.32.0
  remeda: ^2.32.0
  tsdown: ^0.16.8
  typescript: ^5.9.3
