packages:
  - packages/*
  - examples/*

catalog:
  '@types/node': ^20.19.23
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/react-reconciler': 0.32.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-reconciler: 0.32.0
  remeda: ^2.32.0
  tsdown: ^0.15.9
  typescript: ^5.9.3
