blank_issues_enabled: true
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/kubb-labs/kubb/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://discord.gg/shfBFeczrm
    about: Please ask and answer questions here.
