export { defaultParser } from './defaultParser.ts'
export { defineParser } from './defineParser.ts'
export { tsxParser } from './tsxParser.ts'
export { createArrowFunction, createConst, createFunction, createTypeAlias, typescriptParser } from './typescriptParser.ts'
export type { ArrowFunctionNodeProps, ConstNodeProps, FunctionNodeProps, TypeAliasNodeProps } from './typescriptParser.ts'
